#!/bin/bash
# Script de comandos curl para consultar la API de Medula
# Uso: bash curl-commands.sh [email] [password]
# Ejemplo: bash curl-commands.sh javiera.ruiz@medula.cl password123

API="http://localhost:5000/api"

# Parámetros opcionales
USER_EMAIL="${1:-javiera.ruiz@medula.cl}"
USER_PASSWORD="${2:-}"

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         COMANDOS CURL - API MEDULA                             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📧 Usuario de ejemplo: $USER_EMAIL"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "💡 TIP: Puedes usar este script con cualquier usuario:"
echo "   bash curl-commands.sh usuario@email.com password123"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# ============================================================================
# COMANDOS GENÉRICOS PARA BÚSQUEDA
# ============================================================================
echo "🔍 BÚSQUEDA GENÉRICA DE CUALQUIER USUARIO/PACIENTE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Buscar por email:"
echo "   curl -s '$API/users/buscar?q=EMAIL_PARCIAL' | python3 -m json.tool"
echo ""
echo "2️⃣  Buscar por RUT:"
echo "   curl -s '$API/users/buscar?q=RUT' | python3 -m json.tool"
echo ""
echo "3️⃣  Buscar por nombre:"
echo "   curl -s '$API/users/buscar?q=NOMBRE' | python3 -m json.tool"
echo ""
echo "4️⃣  Obtener paciente por ID:"
echo "   curl -s '$API/pacientes/PACIENTE_ID' | python3 -m json.tool"
echo ""
echo "5️⃣  Obtener paciente actual (con token):"
echo "   TOKEN=\$(curl -s -X POST '$API/auth/login' -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"EMAIL\",\"password\":\"PASSWORD\"}' | python3 -c 'import sys,json;print(json.load(sys.stdin)[\"token\"])')"
echo "   curl -s -H \"Authorization: Bearer \$TOKEN\" '$API/pacientes/me' | python3 -m json.tool"
echo ""
echo ""

# ============================================================================
# USUARIOS
# ============================================================================
echo "📋 USUARIOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  Listar todos los usuarios (primeros 5):"
echo "   curl -s '$API/users' | python3 -m json.tool | head -50"
echo ""

echo "2️⃣  Buscar usuario por email:"
echo "   curl -s '$API/users/buscar?q=USUARIO_EMAIL' | python3 -m json.tool"
echo ""

echo "3️⃣  Buscar usuario por RUT:"
echo "   curl -s '$API/users/buscar?q=RUT_USUARIO' | python3 -m json.tool"
echo ""

echo "4️⃣  Obtener usuario por ID:"
echo "   curl -s '$API/users/68ec7cc77c3a8949dac40e65' | python3 -m json.tool"
echo ""

echo "5️⃣  Estadísticas de usuarios:"
echo "   curl -s '$API/users/estadisticas' | python3 -m json.tool"
echo ""

# ============================================================================
# PACIENTES
# ============================================================================
echo "🏥 PACIENTES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  Listar todos los pacientes:"
echo "   curl -s '$API/pacientes' | python3 -m json.tool"
echo ""

echo "2️⃣  Obtener paciente actual (requiere token):"
echo "   TOKEN=\$(curl -s -X POST '$API/auth/login' -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"javiera.ruiz@medula.cl\",\"password\":\"tu_password\"}' | python3 -c 'import sys,json;print(json.load(sys.stdin)[\"token\"])')"
echo "   curl -s -H \"Authorization: Bearer \$TOKEN\" '$API/pacientes/me' | python3 -m json.tool"
echo ""

echo "3️⃣  Obtener paciente por ID:"
echo "   curl -s '$API/pacientes/68ec7cfa7c3a8949dac40e75' | python3 -m json.tool"
echo ""

echo "4️⃣  Buscar pacientes:"
echo "   curl -s '$API/pacientes/buscar?q=javiera' | python3 -m json.tool"
echo ""

# ============================================================================
# RECETAS
# ============================================================================
echo "💊 RECETAS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  Obtener recetas de un paciente (requiere token):"
echo "   TOKEN=\$(curl -s -X POST '$API/auth/login' -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"javiera.ruiz@medula.cl\",\"password\":\"tu_password\"}' | python3 -c 'import sys,json;print(json.load(sys.stdin)[\"token\"])')"
echo "   PID=\$(curl -s -H \"Authorization: Bearer \$TOKEN\" '$API/pacientes/me' | python3 -c 'import sys,json;print(json.load(sys.stdin)[\"_id\"])')"
echo "   curl -s -H \"Authorization: Bearer \$TOKEN\" \"$API/recetas/paciente/\$PID\" | python3 -m json.tool"
echo ""

echo "2️⃣  Migrar IDs de recetas (corregir legacy):"
echo "   curl -s -X POST '$API/recetas/migrate-ids' | python3 -m json.tool"
echo ""

# ============================================================================
# CONSULTAS
# ============================================================================
echo "📝 CONSULTAS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  Listar consultas de un paciente (requiere token):"
echo "   TOKEN=\$(curl -s -X POST '$API/auth/login' -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"javiera.ruiz@medula.cl\",\"password\":\"tu_password\"}' | python3 -c 'import sys,json;print(json.load(sys.stdin)[\"token\"])')"
echo "   PID=\$(curl -s -H \"Authorization: Bearer \$TOKEN\" '$API/pacientes/me' | python3 -c 'import sys,json;print(json.load(sys.stdin)[\"_id\"])')"
echo "   curl -s -H \"Authorization: Bearer \$TOKEN\" \"$API/consultas?paciente=\$PID\" | python3 -m json.tool"
echo ""

echo "2️⃣  Buscar consultas por RUT:"
echo "   curl -s '$API/consultas?rut=167812307' | python3 -m json.tool"
echo ""

# ============================================================================
# MÉDICOS
# ============================================================================
echo "👨‍⚕️ MÉDICOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  Listar todos los médicos:"
echo "   curl -s '$API/medicos' | python3 -m json.tool"
echo ""

echo "2️⃣  Buscar médicos:"
echo "   curl -s '$API/medicos/buscar?q=lopez' | python3 -m json.tool"
echo ""

# ============================================================================
# AUTENTICACIÓN
# ============================================================================
echo "🔐 AUTENTICACIÓN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  Login y obtener token:"
echo "   curl -s -X POST '$API/auth/login' -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"javiera.ruiz@medula.cl\",\"password\":\"tu_password\"}' | python3 -m json.tool"
echo ""

echo "2️⃣  Guardar token en variable:"
echo "   TOKEN=\$(curl -s -X POST '$API/auth/login' -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"javiera.ruiz@medula.cl\",\"password\":\"tu_password\"}' | python3 -c 'import sys,json;print(json.load(sys.stdin)[\"token\"])')"
echo "   echo \$TOKEN"
echo ""

# ============================================================================
# EJEMPLOS COMPLETOS
# ============================================================================
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         EJEMPLOS COMPLETOS                                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📌 Ejemplo 1: Buscar usuario Javiera Ruiz"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
curl -s "$API/users/buscar?q=javiera.ruiz" | python3 -m json.tool
echo ""

echo "📌 Ejemplo 2: Estadísticas generales"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
curl -s "$API/users/estadisticas" | python3 -m json.tool
echo ""

echo "✅ Script completado"
echo ""
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         EJEMPLO: JAVIERA RUIZ (DATOS DE PRUEBA)               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 DATOS DE USUARIO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Usuario ID:  68ec7cc77c3a8949dac40e65"
echo "  Nombre:      Javiera Alejandra Ruiz Mendoza"
echo "  Email:       javiera.ruiz@medula.cl"
echo "  RUT:         167812307"
echo "  Rol:         paciente"
echo ""
echo "🏥 DATOS DE PACIENTE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Paciente ID:       68ec7cfa7c3a8949dac40e75"
echo "  Fecha Nacimiento:  1993-06-01"
echo "  Sexo:              femenino"
echo "  Dirección:         Los Cerezos 890, Quilicura, Santiago"
echo "  Teléfono:          +56909876543"
echo "  Previsión:         FONASA D"
echo "  Estado:            ✅ Activo"
echo ""
echo "⚠️  ALERGIAS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Penicilina"
echo "  2. Mariscos"
echo ""
echo "🩺 ENFERMEDADES CRÓNICAS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Hipertensión arterial"
echo ""
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║    CÓMO ACTUALIZAR ALERGIAS Y ENFERMEDADES CRÓNICAS           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🔧 COMANDO PARA ACTUALIZAR (requiere autenticación):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# 1. Obtener token"
echo "TOKEN=\$(curl -s -X POST '$API/auth/login' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"javiera.ruiz@medula.cl\",\"password\":\"TU_PASSWORD\"}' \\"
echo "  | python3 -c 'import sys,json;print(json.load(sys.stdin)[\"token\"])')"
echo ""
echo "# 2. Actualizar perfil con alergias y enfermedades"
echo "curl -X PUT '$API/pacientes/me' \\"
echo "  -H \"Authorization: Bearer \$TOKEN\" \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"fecha_nacimiento\": \"1993-06-01\","
echo "    \"sexo\": \"femenino\","
echo "    \"direccion\": \"Los Cerezos 890, Quilicura, Santiago\","
echo "    \"telefono\": \"+56909876543\","
echo "    \"prevision\": \"FONASA D\","
echo "    \"alergias\": [\"Penicilina\", \"Mariscos\"],"
echo "    \"enfermedades_cronicas\": [\"Hipertensión\"]"
echo "  }' | python3 -m json.tool"
echo ""
echo "# 3. Verificar actualización"
echo "curl -s -H \"Authorization: Bearer \$TOKEN\" '$API/pacientes/me' | python3 -m json.tool"
echo ""
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         COMANDOS ÚTILES PARA BÚSQUEDAS                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📌 Buscar paciente de Javiera:"
echo "   curl -s '$API/pacientes/68ec7cfa7c3a8949dac40e75' | python3 -m json.tool"
echo ""
echo "📌 Buscar todas las consultas de Javiera (requiere token):"
echo "   TOKEN=\$(curl -s -X POST '$API/auth/login' -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"javiera.ruiz@medula.cl\",\"password\":\"PASSWORD\"}' | python3 -c 'import sys,json;print(json.load(sys.stdin)[\"token\"])')"
echo "   curl -s -H \"Authorization: Bearer \$TOKEN\" '$API/consultas?paciente=68ec7cfa7c3a8949dac40e75' | python3 -m json.tool"
echo ""
echo "📌 Buscar recetas de Javiera (requiere token):"
echo "   curl -s -H \"Authorization: Bearer \$TOKEN\" '$API/recetas/paciente/68ec7cfa7c3a8949dac40e75' | python3 -m json.tool"
echo ""
echo "📌 Buscar por RUT (sin autenticación):"
echo "   curl -s '$API/users/buscar?q=167812307' | python3 -m json.tool"
echo "   curl -s '$API/consultas?rut=167812307' | python3 -m json.tool"
echo ""
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         ESTRUCTURA DE DATOS - REFERENCIA                      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 Modelo Usuario:"
echo "   {" 
echo "     \"_id\": \"ObjectId\","
echo "     \"nombre\": \"string\","
echo "     \"email\": \"string\","
echo "     \"rut\": \"string\","
echo "     \"rol\": \"paciente|medico|administrador\","
echo "     \"activo\": \"boolean\""
echo "   }"
echo ""
echo "📦 Modelo Paciente:"
echo "   {"
echo "     \"_id\": \"ObjectId\","
echo "     \"usuario_id\": \"ObjectId (ref: Usuario)\","
echo "     \"fecha_nacimiento\": \"Date\","
echo "     \"sexo\": \"masculino|femenino|otro\","
echo "     \"direccion\": \"string\","
echo "     \"telefono\": \"string\","
echo "     \"prevision\": \"string\","
echo "     \"alergias\": [\"string\", \"string\"],          ← Array de strings"
echo "     \"enfermedades_cronicas\": [\"string\"],        ← Array de strings"
echo "     \"activo\": \"boolean\""
echo "   }"
echo ""
echo "📦 Modelo Receta:"
echo "   {"
echo "     \"_id\": \"ObjectId\","
echo "     \"paciente_id\": \"ObjectId (ref: Paciente)\","
echo "     \"medico_id\": \"ObjectId (ref: Usuario)\","
echo "     \"fecha_emision\": \"Date\","
echo "     \"medicamentos\": ["
echo "       {"
echo "         \"nombre\": \"string\","
echo "         \"dosis\": \"string\","
echo "         \"frecuencia\": \"string\","
echo "         \"duracion\": \"string\","
echo "         \"instrucciones\": \"string\""
echo "       }"
echo "     ],"
echo "     \"activa\": \"boolean\""
echo "   }"
echo ""
echo "📦 Modelo Consulta:"
echo "   {"
echo "     \"_id\": \"ObjectId\","
echo "     \"paciente_id\": \"ObjectId (ref: Paciente)\","
echo "     \"cita_id\": \"ObjectId\","
echo "     \"motivo\": \"string\","
echo "     \"diagnostico\": \"string\","
echo "     \"receta\": { /* Receta embebida */ }"
echo "   }"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ Script completado con información de referencia guardada"
echo "═══════════════════════════════════════════════════════════════"
